#8 Improve docker-compose file
jerimumhs/transparencia-api pull request #9
Opened 2019-10-02 03:43 UTC by exageraldo

Centraliza todas as configurações no mesmo arquivo e remove o pgadmin.

2019-10-03 18:37 UTC, rodrigondec requested changes
Vou subir as alterações relativas à esses comentários

2019-10-03 18:37 UTC, rodrigondec commented on docker-compose.yml
> +    command:
Esse comando roda quando o container é criado. Então não está usando cache de build de imagem. Toda vez que iniciar o container vai instalar novamente as dependências

2019-10-03 18:37 UTC, rodrigondec commented on docker-compose.yml
> +      - FLASK_APP=transparencia_api
já temos um .env.example para essas variáveis. É bom parametrizar

2019-10-04 00:06 UTC, exageraldo commented on docker-compose.yml
> +    command:
Teoricamente o container é para ser reiniciado mesmo. Acho que não tem problema nisso.

2019-10-04 00:08 UTC, exageraldo commented on docker-compose.yml
> +      - FLASK_APP=transparencia_api
Estava pensando em enfiar tudo dentro do .env e não colocar nada aqui. Ainda estou analisando isso melhor.

2019-10-04 00:12 UTC, rodrigondec commented on docker-compose.yml
> +    command:
Mas estou falando que toda vez que iniciar o container vai baixar novamente as libs. Se deixar no Dockerfile, as libs ficam na imagem que já foi buildada

2019-10-04 22:32 UTC, rodrigondec commented on docker-compose.yml
> +      - FLASK_APP=transparencia_api
Sim, eu tbm fiz dessa forma. Assim não deixa exposto as configurações do postgres tbm. Eu subi essa alteração já, dá uma olhada

2019-10-04 22:33 UTC, rodrigondec approved these changes

2019-11-04 22:45 UTC, merged